apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
spec:
  containers:
  - image: mysql
    name: mysql
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-data  # declaration de l'objet volume
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: eazytraining
      - name: MYSQL_USER
        value: eazy
      - name: MYSQL_PASSWORD
        value: eazy
  volumes:                          # initialisation/definition de l'objet volume
  - name: mysql-data
    hostPath:
      # chemin du dossier sur l'hôte(dans le quel les données seront conservés)
      path: /data-volume
      # ce champ est optionnel si le dossier de montage nexiste pas il le creer 
      type: DirectoryOrCreate
